package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/MaximoCoder/Enveil/cli/internal/serverclient"
	"github.com/MaximoCoder/Enveil/cli/internal/ui"
	"github.com/MaximoCoder/Enveil/core/config"
	"github.com/MaximoCoder/Enveil/core/vault"
	"github.com/spf13/cobra"
)

var exportCmd = &cobra.Command{
	Use:   "export",
	Short: "Generate a temporary .env file in the current directory",
	RunE:  runExport,
}

func init() {
	rootCmd.AddCommand(exportCmd)
}

func runExport(cmd *cobra.Command, args []string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	if !cfg.IsInitialized() {
		return fmt.Errorf("enveil is not initialized, run 'enveil init' first")
	}

	var vars map[string]string

	if cfg.HasServer() {
		client := serverclient.New(cfg.ServerURL, cfg.ServerAPIKey)
		vars, err = client.GetVariables(cfg.ActiveProject, cfg.ActiveEnv)
		if err != nil {
			return fmt.Errorf("error fetching variables from server: %w", err)
		}
	} else {
		masterKeyHex, err := promptAndDeriveKey(cfg)
		if err != nil {
			return err
		}

		v, err := vault.Open(cfg.VaultPath, masterKeyHex)
		if err != nil {
			return err
		}
		defer v.Close()

		projectID, _, err := v.GetProjectByPath(getCurrentDir())
		if err != nil {
			return err
		}
		if projectID == 0 {
			return fmt.Errorf("this directory is not registered, run 'enveil init'")
		}

		envID, err := v.GetEnvironment(projectID, cfg.ActiveEnv)
		if err != nil {
			return err
		}
		if envID == 0 {
			return fmt.Errorf("environment '%s' not found", cfg.ActiveEnv)
		}

		vars, err = v.GetVariables(envID)
		if err != nil {
			return err
		}
	}

	if len(vars) == 0 {
		return fmt.Errorf("no variables in environment '%s'", cfg.ActiveEnv)
	}

	// Build .env file content
	var lines []string
	lines = append(lines, "# Generated by Enveil - DO NOT commit this file")
	lines = append(lines, fmt.Sprintf("# Project: %s | Environment: %s", cfg.ActiveProject, cfg.ActiveEnv))
	lines = append(lines, "")

	for k, val := range vars {
		if strings.ContainsAny(val, " \t\n#$") {
			lines = append(lines, fmt.Sprintf(`%s="%s"`, k, val))
		} else {
			lines = append(lines, fmt.Sprintf("%s=%s", k, val))
		}
	}

	content := strings.Join(lines, "\n") + "\n"

	envFilePath := filepath.Join(getCurrentDir(), ".env")
	if err := os.WriteFile(envFilePath, []byte(content), 0600); err != nil {
		return fmt.Errorf("error writing .env: %w", err)
	}

	if err := ensureGitignore(getCurrentDir()); err != nil {
		ui.Warning("Could not update .gitignore: %v", err)
	}

	ui.Success(".env generated at %s", envFilePath)
	ui.Warning("Delete it when done with: rm .env")
	return nil

}

// ensureGitignore adds .env to .gitignore if its not already there
func ensureGitignore(dir string) error {
	gitignorePath := filepath.Join(dir, ".gitignore")

	//  Read current content if exists
	content, err := os.ReadFile(gitignorePath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	// Check if .env is already in .gitignore
	for _, line := range strings.Split(string(content), "\n") {
		if strings.TrimSpace(line) == ".env" {
			return nil
		}
	}

	// Add .env to .gitignore
	f, err := os.OpenFile(gitignorePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	// If file exists and does not end in newline, add one first
	if len(content) > 0 && content[len(content)-1] != '\n' {
		fmt.Fprintln(f)
	}

	fmt.Fprintln(f, ".env")
	ui.Info(".env added to .gitignore")
	return nil
}